触发构建

diff --git a/.github/workflows/build-server-x64.yml b/.github/workflows/build-server-x64.yml
--- a/.github/workflows/build-server-x64.yml
+++ b/.github/workflows/build-server-x64.yml
@@ -16,7 +16,52 @@ jobs:
       ARCH: x64
       OS: linux
     steps:
+      - name: Free Disk Space
+        uses: jlumbroso/free-disk-space@main
+        with:
+          tool-cache: false
+          android: true
+          dotnet: true
+          haskell: true
+          large-packages: true
+          docker-images: true
+          swap-storage: true
       - name: Checkout code
         uses: actions/checkout@v4
       - name: setup and build
         uses: ./.github/actions/build-images/server
+  push-image:
+    needs: [build-server]
+    runs-on: ubuntu-22.04
+    permissions:
+      contents: read
+      packages: write
+    env:
+      ARCH: x64
+      OS: linux
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Download rancher image
+        uses: actions/download-artifact@v4
+        with:
+          pattern: "rancher-${{ env.OS }}-${{ env.ARCH }}"
+          path: /tmp
+      - name: Setup Environment Variables
+        uses: ./.github/actions/setup-tag-env
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push server image
+        shell: bash
+        run: |
+          image_id=$(docker load --input /tmp/rancher-${{ env.OS }}-${{ env.ARCH }}/rancher-${{ env.OS }}-${{ env.ARCH }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+          if [ -z "$image_id" ]; then
+            echo "Error: Failed to load image from tarball!"
+            exit 1
+          fi
+          docker tag "$image_id" ghcr.io/${{ github.repository_owner }}/rancher:${{ env.TAG }}-${{ env.ARCH }}
+          docker push ghcr.io/${{ github.repository_owner }}/rancher:${{ env.TAG }}-${{ env.ARCH }}
